### PR TITLE
Various bugfixes, but would need testing with default header. 

### PR DESCRIPTION
**Pull request by ggppjj**
The fixes are listed in the various commit messages, and it would need testing with how it currently interacts with a non-default header image. I've tested it with a sub that has a default header image, and it seems to work perfectly. Again, tests are needed.

### CODE REVIEW

**Comment by chtzvt** [comment]
I'll test this in /r/eliteshell and report back with my findings.

**Comment by ggppjj** [comment]
Based on what I'm seeing, you're currently testing the DOS version. As
you've noticed, there are some hard-coded sub-specific strings (pzwmcss,
Zork copyright).The l33t haxx0r version is unchanged in those ways.

**Comment by chtzvt** [comment]
Alright, I can confirm that the stylesheet functions correctly, with the following caveats: 
- the final rule in the sheet for .tabmenu uses () instead of {}, which throws an error.
- this pull request was opened with the DOS theme from your DOS branch, rather than with the modified eliteshell theme.

Outside of that, though, the DOS theme looks incredible!

**Comment by ggppjj** [comment]
Ah, poop. Lemme send the right pull.

**Comment by chtzvt** [comment]
That said, I will have to close this pull request, as merging would replace eliteshell with the DOS theme. Could you open a new one with the master branch of your fork as the source?

**Comment by chtzvt** [comment]
Great, thank you!

**Pull request closed without merging**
