### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by chtzvt** [comment]
Merged! Many thanks for the PR, and happy holidays :)

**Comment by chtzvt** [comment]
Sorry- did I utterly fail to merge this in properly? I could have sworn I clicked merge after I commented, but after looking at the repo commit history seems to say otherwise. 

Very sorry if so, I was a bit scatterbrained at the time. But I'd still love to have your changes!

**Comment by ghost** [comment]
Oops, sorry - I didn't notice it wasn't merged. I was just "cleaning up". It seems that I can't reopen, though. It might be because I deleted my fork. I usually do that after making a one-time contribution.

**Comment by chtzvt** [comment]
No worries- I think I can still get to the diff from this comment thread. If I can, I'll grab your changes from there and push them in.

Once again, I'm very sorry about this mixup!! Can't believe I forgot to merge- I suppose I'm a bit of a doofus.

**Comment by chtzvt** [comment]
All done! Thanks again for the contribution:)

**Pull request closed without merging**
